# Generated by Django 4.1 on 2022-09-07 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex='^\\+?7?\\d{11,12}$')], verbose_name='Номер телефона'),
        ),
    ]
